### ISSUE TITLE
3도 변수화 해주세요 

### ISSUE THREAD

**Issue by niceaji** [z-hoony/start-fe#1]
https://github.com/z-hoony/start-fe/blob/fd1eabed79ec23bce989bd5655bffeace40285c8/04/quiz-1.js#L17

**Comment by z-hoony** [comment]
상수를 변수화 했습니다

**Comment by niceaji** [comment]
@z-hoony 네 확인했습니다.
https://github.com/z-hoony/start-fe/commit/196aba13b031fb5bef7d12066e04b2b31bddfa66

이런식으로 커밋 링크를 남겨주시면 확인하기가 편합니다 :)
